###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = kitty 
$fileManager = nautilus
$menu = pidof wofi || wofi -a --conf ~/.config/wofi/config --style ~/.config/wofi/style.css

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/environment.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/ui.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/keybindings.conf
