##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


windowrule {
  name = windowrule-3
  float = on
  match:class = xdg-desktop-portal-gtk
}

windowrule {
  name = windowrule-4
  float = on
  match:class = org.gnome.Calculator
}

windowrule {
  name = windowrule-5
  float = on
  match:class = org.gnome.Loupe
}

windowrule {
  name = windowrule-6
  float = on
  match:class = nm-connection-editor
}

windowrule {
  name = windowrule-7
  float = on
  match:class = blueman-manager
}

windowrule {
  name = windowrule-8
  float = on
  match:class = org.pulseaudio.pavucontrol
}

windowrule {
  name = windowrule-9
  float = on
  match:class = tuned-gui
}
